Repository exonet/exonet-api-python, pull requests merged in 2021-11, with the labels that each got.

#25 Decode JSON content when parsing API results
  .editorconfig
  .github/workflows/ci.yaml
  README.rst
  exonetapi/result/Parser.py
  setup.py
  tests/result/testParser.py
  tests/testRequestBuilder.py
Labels: bugfix

#27 Update version number
  .github/release-drafter.yml
  setup.py
Labels: maintenance

#28 Automatically publish packages to PyPI
  .github/workflows/ci.yaml
  .github/workflows/tests.yaml
  README.rst
  setup.py
Labels: ci
